apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
  namespace: lithoapp
type: Opaque
stringData:
  TUNNEL_ID: "replace-with-cloudflare-tunnel-uuid"
  credentials.json: |
    {
      "AccountTag": "replace-with-account-tag",
      "TunnelSecret": "replace-with-tunnel-secret",
      "TunnelID": "replace-with-cloudflare-tunnel-uuid"
    }

