apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: lithoapp
spec:
  type: ClusterIP
  selector:
    app: patient-service
  ports:
    - name: http
      port: 8086
      targetPort: http

