-- =============================================================
--  LithoApp - Drainage Service
--  Schema script for database: drainage_db
--  Run this inside DBeaver connected to drainage_db
-- =============================================================


-- -------------------------------------------------------------
--  STEP 1 - Drop existing objects (safe re-run)
-- -------------------------------------------------------------

DROP TRIGGER  IF EXISTS trg_drainages_updated_at ON drainages;
DROP FUNCTION IF EXISTS fn_set_updated_at();
DROP TABLE    IF EXISTS drainages;


-- -------------------------------------------------------------
--  STEP 2 - Create table
--
--  Column names follow Hibernate's default camelCase → snake_case
--  conversion (e.g. patientId → patient_id).
--
--  Enum columns are VARCHAR because Hibernate stores Java enums
--  as plain strings with @Enumerated(EnumType.STRING).
--  CHECK constraints enforce the allowed values at DB level.
-- -------------------------------------------------------------

CREATE TABLE drainages
(
    -- primary key: UUID generated by the application (GenerationType.UUID)
    id                      UUID         NOT NULL,

    -- external service references (no FK — other services are separate)
    patient_id              BIGINT       NOT NULL,
    doctor_id               BIGINT       NOT NULL,

    -- clinical fields
    drainage_type           VARCHAR(20)  NOT NULL,   -- JJ | URETERAL | NEPHROSTOMY
    side                    VARCHAR(20)  NOT NULL,   -- LEFT | RIGHT | BILATERAL
    placed_at               DATE         NOT NULL,
    planned_removal_date    DATE,
    removed_at              DATE,
    status                  VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE | REMOVED
    jj_type                 VARCHAR(20),             -- STANDARD_6F | LARGE_7F | BIODEGRADABLE | METALLIC
    notes                   TEXT,

    -- notification tracking (populated by the daily scheduler)
    pre_reminder_sent_at    TIMESTAMP,
    day_of_reminder_sent_at TIMESTAMP,

    -- audit timestamps (managed by Hibernate @CreationTimestamp / @UpdateTimestamp)
    created_at              TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at              TIMESTAMP    NOT NULL DEFAULT now(),

    -- ---------------------------------------------------------
    --  PRIMARY KEY
    -- ---------------------------------------------------------
    CONSTRAINT pk_drainages
        PRIMARY KEY (id),

    -- ---------------------------------------------------------
    --  ENUM VALUE CHECKS
    -- ---------------------------------------------------------
    CONSTRAINT chk_drainage_type
        CHECK (drainage_type IN ('JJ', 'URETERAL', 'NEPHROSTOMY')),

    CONSTRAINT chk_drainage_side
        CHECK (side IN ('LEFT', 'RIGHT', 'BILATERAL')),

    CONSTRAINT chk_drainage_status
        CHECK (status IN ('ACTIVE', 'REMOVED')),

    CONSTRAINT chk_jj_type_value
        CHECK (
            jj_type IS NULL
            OR jj_type IN ('STANDARD_6F', 'LARGE_7F', 'BIODEGRADABLE', 'METALLIC')
        ),

    -- ---------------------------------------------------------
    --  BUSINESS RULE CHECKS
    -- ---------------------------------------------------------

    -- jj_type must be set when drainage_type = JJ, and null otherwise
    CONSTRAINT chk_jj_type_only_for_jj
        CHECK (
            (drainage_type = 'JJ'  AND jj_type IS NOT NULL)
            OR
            (drainage_type <> 'JJ' AND jj_type IS NULL)
        ),

    -- planned removal date must not be before insertion date
    CONSTRAINT chk_planned_after_placed
        CHECK (
            planned_removal_date IS NULL
            OR planned_removal_date >= placed_at
        ),

    -- actual removal date must not be before insertion date
    CONSTRAINT chk_removed_after_placed
        CHECK (
            removed_at IS NULL
            OR removed_at >= placed_at
        )
);


-- -------------------------------------------------------------
--  STEP 3 - Partial unique index
--
--  A patient cannot have two ACTIVE drainages of the same
--  type on the same side. Multiple REMOVED rows for the same
--  combination are allowed (hence partial, not a plain UNIQUE).
-- -------------------------------------------------------------

CREATE UNIQUE INDEX uix_active_drainage_per_patient
    ON drainages (patient_id, drainage_type, side)
    WHERE (status = 'ACTIVE');


-- -------------------------------------------------------------
--  STEP 4 - Performance indexes
-- -------------------------------------------------------------

CREATE INDEX idx_drainages_patient_id
    ON drainages (patient_id);

CREATE INDEX idx_drainages_status
    ON drainages (status);

-- used by the scheduler to find upcoming removals
CREATE INDEX idx_drainages_planned_removal_active
    ON drainages (planned_removal_date)
    WHERE (status = 'ACTIVE');


-- -------------------------------------------------------------
--  STEP 5 - Auto-update trigger for updated_at
--
--  Hibernate handles this in the application layer.
--  The trigger is a safety net for direct SQL edits in DBeaver.
-- -------------------------------------------------------------

CREATE OR REPLACE FUNCTION fn_set_updated_at()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_drainages_updated_at
    BEFORE UPDATE ON drainages
    FOR EACH ROW
    EXECUTE FUNCTION fn_set_updated_at();
