spring:
  application:
    name: api-gateway
  cloud:
    # Disables fetching configuration from Spring Cloud Config Server
    config:
      enabled: false
    # Disables registration and fetching from Eureka Discovery Server
    discovery:
      enabled: false
    #keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/my-realm
server:
  port: 9090
  servlet:
    context-path: /api-gateway

#eureka server
eureka:
  client:
    # Explicitly prevents the Eureka client from running
    enabled: false
    register-with-eureka: false
    fetch-registry: false

