apiVersion: v1
kind: Service
metadata:
  name: drainage-service
  namespace: lithoapp
spec:
  type: ClusterIP
  selector:
    app: drainage-service
  ports:
    - name: http
      port: 8084
      targetPort: http

