apiVersion: v1
kind: Service
metadata:
  name: episode-service
  namespace: lithoapp
spec:
  type: ClusterIP
  selector:
    app: episode-service
  ports:
    - name: http
      port: 8085
      targetPort: http

