apiVersion: v1
kind: Secret
metadata:
  name: lithoapp-secrets
  namespace: lithoapp
type: Opaque
stringData:
  POSTGRES_USER: "lithoapp"
  POSTGRES_PASSWORD: "replace-with-strong-postgres-password"
  PATIENT_DB_NAME: "patient_db"
  EPISODE_DB_NAME: "episode_db"
  ANALYSIS_DB_NAME: "bilan_db"
  DRAINAGE_DB_NAME: "drainage_db"
  KEYCLOAK_DB_NAME: "keycloak_db"

  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "replace-with-strong-keycloak-admin-password"
  KC_DB_USERNAME: "keycloak"
  KC_DB_PASSWORD: "replace-with-strong-keycloak-db-password"

  MINIO_ROOT_USER: "minio-root-admin"
  MINIO_ROOT_PASSWORD: "replace-with-strong-minio-root-password"
  STORAGE_MINIO_ACCESS_KEY: "analysis-service"
  STORAGE_MINIO_SECRET_KEY: "replace-with-strong-analysis-minio-password"

